# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: usersdb1

  #adminer:
    #image: adminer
    #restart: always
    ports:
      - 3306:3306
     # - 19999:8080
    networks:
        - spring-cloud-network
    container_name: mysql

  gluebin-service:
    build:
      context: /home/jthancoc/build/docker-experiments/gluebin/docker/
      dockerfile: gluebin-service-dockerfile
    image: gluebin-server:latest
    ports:
          - 18888:8080
    networks:
          - spring-cloud-network
    depends_on:
        - db
    container_name:
        gluebin-service
  web:
   image: reverse-proxy:latest
   volumes:
   - ./web:/usr/share/nginx/html
   ports:
     - 19999:80
   networks:
     - spring-cloud-network
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data
    container_name:
      minio
    networks:
     - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
